'use client';
import { useEffect, useState } from 'react';
import { Lightbulb } from 'lucide-react';
import {
  AuditBrowser,
  AuditBrowserItem,
} from '@/components/audit/AuditBrowser';

/**
 * Client companion of /audits/page.tsx. Fetches the aggregate
 * dataset, then hands it to <AuditBrowser>. The project scope is
 * driven entirely by `scopedProjectId` which the server component
 * derives from the top navbar selector cookie.
 */
export function AuditsClient({
  scopedProjectId,
  scopedProjectName,
}: {
  scopedProjectId: string | null;
  scopedProjectName: string | null;
}) {
  const [items, setItems] = useState<AuditBrowserItem[] | null>(null);
  const [counts, setCounts] = useState<{
    projects: number;
    advices: number;
    withScore: number;
  } | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    void (async () => {
      setLoading(true);
      try {
        const r = await fetch('/api/audits/aggregate');
        const j = await r.json();
        setItems(j.items ?? []);
        setCounts(j.counts ?? null);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  // The aggregate endpoint returns data for every project. When the
  // top selector scopes to one project, keep only its rows so the
  // tiles, the list, and the counts reflect that project only.
  const scopedItems = scopedProjectId
    ? (items ?? []).filter((it) => it.projectId === scopedProjectId)
    : items;

  // Diagnose a common situation: the user has audit rows but no
  // scores at all (parse failures, legacy rows, etc). v5: each row
  // carries a single category-level score on `it.score`, so this is
  // a one-line scan.
  const hasAnyScore =
    !!scopedItems &&
    scopedItems.some((it) => typeof it.score === 'number');
  const showLegacyBanner =
    !loading && !!scopedItems && scopedItems.length > 0 && !hasAnyScore;

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Lightbulb size={22} className="text-amber-500" />
          Audits
          {scopedProjectName ? (
            <span className="text-base font-normal text-slate-500">
              · {scopedProjectName}
            </span>
          ) : (
            <span className="text-xs font-normal text-slate-500">
              — cross-project priority list
            </span>
          )}
        </h1>
        <p className="text-sm text-slate-500 mt-1">
          Select one or more points from the same project to open a
          chat pre-filled with the full context of your selection.
          {counts && !scopedProjectId && (
            <span className="ml-2">
              ({counts.projects} project(s) • {counts.advices} row(s))
            </span>
          )}
        </p>
      </div>

      {showLegacyBanner && (
        <div className="rounded-md border border-amber-300 dark:border-amber-700 bg-amber-50 dark:bg-amber-950/30 p-3 text-sm">
          <b className="text-amber-800 dark:text-amber-300">
            Scores missing on {scopedItems!.length} audit row(s).
          </b>{' '}
          <span className="text-amber-900/80 dark:text-amber-200/80">
            These rows were generated by an older audit format (no
            per-axis scoring). Re-run the <b>Priority audit</b> task on{' '}
            {scopedProjectName
              ? <>project <b>{scopedProjectName}</b></>
              : 'each affected project'}{' '}
            to populate the 6-axis scoring tiles.
          </span>
        </div>
      )}

      {loading ? (
        <p className="text-sm text-slate-500">Loading…</p>
      ) : !scopedItems || scopedItems.length === 0 ? (
        <div className="border border-dashed border-slate-300 dark:border-slate-700 rounded-md p-6 text-center">
          <p className="text-sm text-slate-500">
            {scopedProjectName
              ? <>No audit generated yet for <b>{scopedProjectName}</b>. Open its dashboard and click <b>Run</b> on the Priority audit task.</>
              : <>No audit generated yet. Open a project dashboard and click <b>Run</b> on its Priority audit task.</>}
          </p>
        </div>
      ) : (
        <AuditBrowser
          items={scopedItems}
          scopedProjectId={scopedProjectId}
        />
      )}
    </div>
  );
}
